spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gameplay?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  address: 192.168.5.178
security:
  jwt:
    token:
      secret-key: 53cr37
spring-doc:
  paths-to-match:
    - /**
  swagger-ui:
    use-root-path: true
